### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/web-money-manager-ex#16]
Is this "Money Manager Ex - Web App" applicatin still supported and being developed?

I've installed version 1.0.4 on my Linux server. When I try add a transaction via the /new_transaction.php page the 'Account' and 'To Account' fields are blank. They don't detect the accounts that I've created in my MMX database.

Is this a "user issue"? Or is there a problem with Money Manager Ex - Web App?

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3643

**Comment by maksimdzmitryew** [comment]
Hi @luisdev. Let me take courage and confirm that Yes, WebApp will enjoy more attention and support from now. 

As for the issue you've faced. I've also been there )) Seems like one has to explicitly Refresh WebApp from Desktop App.

Please, try the following:

1) Options -> Network -> WebApp Settings -> Fill in Url and GUID … OK
2) Tools -> Refresh WebApp … OK
3) Profit!

Let me know if it worked for you
