### ISSUE TITLE
Wrong name

### ISSUE THREAD

**Issue by Karim-0** [moneymanagerex/web-money-manager-ex#23]
https://github.com/moneymanagerex/web-money-manager-ex/blob/d5ae3da60f4e0d489067c57c45e2c52d10cdbfe7/WebApp/settings.php#L89

I think you changed the "functions-1.0.4.js" to "functions-1.1.0.js" but in the "settings.php" is still as it was before.

That is causing a real mess.

**Comment by maksimdzmitryew** [comment]
@KarimCDTechnologia thank you for the feedback and mess report. Truly sorry for this

Please, check the latest update. It should be fixed by now. 

Let me know if it helped.

**Comment by lucaritossa** [comment]
This issue is now fixed. It can be closed.
