### ISSUE TITLE
Compatibility PHP 8

### ISSUE THREAD

**Issue by sharkyiwc** [moneymanagerex/web-money-manager-ex#33]
Hello,

I updated my server with PHP 8 and I have problems with the import.
Can you confirm the compatibility with PHP 8?
If i use PHP 7.4 OK

Thanks

**Comment by n-stein** [comment]
I pushed some fixes in PR #35 to resolve the issues with the PHP upgrade. Not seeing any problems with PHP 8.1 in Docker version.

**Comment by Letme** [comment]
Based on time elapsed and support in recent release notes, I think this issue can be closed as PHP 8 support is now established.
