### ISSUE TITLE
Webapp issue - help please!

### ISSUE THREAD

**Issue by berkeseva** [moneymanagerex/web-money-manager-ex#34]
Hi, 

when i start the desktop app i get the following error message:

![Képkivágás](https://user-images.githubusercontent.com/118137447/203438500-05bedc0d-cdc7-4324-b88c-cdf1245b5245.PNG)
java is enabled in the browser, what could be wrong?

Thx for the help

**Comment by berkeseva** [comment]
Hi,

I tried another host, but Webapp doesn't work. Help, plese
![image](https://user-images.githubusercontent.com/118137447/203869261-c10d141b-e57b-496e-823e-f9832d466514.png)

**Comment by wolfsolver** [comment]
Can you please share configuration in desktop app under network?

**Comment by berkeseva** [comment]
Hi, the problem has since been resolved, thank you very much.
However, I am very sorry that the android support has been discontinued.

Best regards
Üdvözlettel
Berkesné Éva

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
24.
01. 07. 21:55:22

wolfsolver ***@***.***> ezt írta (időpont: 2024. jan. 7., V,
21:51):

**Comment by wolfsolver** [comment]
Android project was reborn! Thanks to @guanlisheng
Give a try to
https://github.com/moneymanagerex/android-money-manager-ex/releases

**Comment by berkeseva** [comment]
Wow, I am very happy about that! :)

Thanks, I'll check it out!


Berkesné Éva
+36-30-559-0141


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
24.
01. 07. 22:06:14

wolfsolver ***@***.***> ezt írta (időpont: 2024. jan. 7., V,
21:59):

**Comment by wolfsolver** [comment]
Can be closed?

**Comment by berkeseva** [comment]
> Can be closed?

Yes, it can be closed
