### ISSUE TITLE
Unable to upload attachement

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/web-money-manager-ex#36]
I try to upload an attachment in a new trasaction, but seems that no file is transfert.
after transaction_new, the insert.php is called with
`Date=2022-12-10&Status=&Type=Withdrawal&Account=######&Payee=#######&Category=######&SubCategory=#######&Amount=###&Notes=some nomes&fileToUpload=sample_file_name.pdf&SubmitButton= `
but no file is upload to webserver

**Comment by nixuno** [comment]
Try adding the following to your `.htaccess` file:

```
php_value upload_max_filesize 10M
php_value post_max_size 20M
php_value memory_limit 32M
```

This worked for me when I was unable to upload attachments from my phone.

Additionally, if you're running the Docker version of this, you'll have to give write permissions to the `/var/www/html/attachments` directory in the container to the `www-data` user.

**Comment by wolfsolver** [comment]
just tested on latest 1.2.2 - no issue
