### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by giac1** [moneymanagerex/web-money-manager-ex#7]
Hi,
I tried to install this version (1.0.2) MMEX WebApp on a server, i followed the instruction, after the installation when i try to connect to it i got stuck on page "settings.php": i can insert User and Password but i can't go forward -- i can't see any confirm button, or next --; i tried with Chrome and Firefox.
The server has PHP 5..4.43 and PDO SQLite active.

Thank you

**Comment by gelse** [comment]
I had the same problem first, the problem was that the user of the webserver (www-data usually) did not have write-rights on the filesystem.
A chown -R www-data:www-data [directory] did the trick.

**Comment by gabriele-v** [comment]
Yes, I confirm that webserver user has to have write rights on folders

**Comment by giac1** [comment]
Thank you, it worked
